version: '3.8'

services:
  backend:
    image: yanwen1/ecommerce_backend:latest
    environment:
      - DB_HOST=${rds_endpoint}
    
    ports:
      - "8000:8000"
    command: >  
          sh -c "python manage.py migrate &&
                python manage.py dumpdata --database=sqlite --natural-foreign --natural-primary -e contenttypes -e auth.Permission --indent 4 > datadump.json &&
                python manage.py loaddata datadump.json &&
                rm -f db.sqlite3 &&
                python manage.py runserver 0.0.0.0:8000"

  frontend:
    image: yanwen1/ecommerce_frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
